language: java
jdk: oraclejdk8
before_install:
  - chmod +x mvnw
sudo: required

services:
  - docker
after_success:
- docker login -u bassey3 -p Calabar1
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- export IMAGE_NAME=bassey3/chasis
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME